// PC Components Database - 2024 Latest Hardware with Realistic Pricing
const COMPONENTS_DATA = {
    cpu: [
        // Intel 14th Gen (Raptor Lake Refresh)
        {
            id: 'cpu_1',
            name: 'Intel Core i9-14900KS',
            brand: 'Intel',
            price: 899000,
            originalPrice: 999000,
            specs: '24 cores (8P+16E), 32 threads, 6.0 GHz boost',
            features: ['Overclockable', 'PCIe 5.0', 'DDR5-5600'],
            socket: 'LGA1700',
            cores: 24,
            threads: 32,
            baseClock: 3.2,
            boostClock: 6.0,
            tdp: 150,
            powerDraw: 253,
            performanceScore: 98,
            category: 'flagship',
            compatibility: ['Z790', 'Z690', 'B760', 'H770'],
            image: '🔥'
        },
        {
            id: 'cpu_2',
            name: 'Intel Core i7-14700K',
            brand: 'Intel',
            price: 549000,
            originalPrice: 599000,
            specs: '20 cores (8P+12E), 28 threads, 5.6 GHz boost',
            features: ['Overclockable', 'PCIe 5.0', 'DDR5-5600'],
            socket: 'LGA1700',
            cores: 20,
            threads: 28,
            baseClock: 3.4,
            boostClock: 5.6,
            tdp: 125,
            powerDraw: 190,
            performanceScore: 92,
            category: 'high-end',
            compatibility: ['Z790', 'Z690', 'B760', 'H770'],
            image: '💎'
        },
        {
            id: 'cpu_3',
            name: 'Intel Core i5-14600K',
            brand: 'Intel',
            price: 399000,
            originalPrice: 439000,
            specs: '14 cores (6P+8E), 20 threads, 5.3 GHz boost',
            features: ['Overclockable', 'PCIe 5.0', 'DDR5-5600'],
            socket: 'LGA1700',
            cores: 14,
            threads: 20,
            baseClock: 3.5,
            boostClock: 5.3,
            tdp: 125,
            powerDraw: 154,
            performanceScore: 85,
            category: 'mainstream',
            compatibility: ['Z790', 'Z690', 'B760', 'H770'],
            image: '⚡'
        },
        // AMD Ryzen 9000 Series (Zen 5)
        {
            id: 'cpu_4',
            name: 'AMD Ryzen 9 9950X',
            brand: 'AMD',
            price: 829000,
            originalPrice: 899000,
            specs: '16 cores, 32 threads, 5.7 GHz boost',
            features: ['Zen 5', 'PCIe 5.0', 'DDR5-5200'],
            socket: 'AM5',
            cores: 16,
            threads: 32,
            baseClock: 4.3,
            boostClock: 5.7,
            tdp: 170,
            powerDraw: 230,
            performanceScore: 96,
            category: 'flagship',
            compatibility: ['X870E', 'X870', 'X670E', 'X670', 'B650E', 'B650'],
            image: '🚀'
        },
        {
            id: 'cpu_5',
            name: 'AMD Ryzen 7 9700X',
            brand: 'AMD',
            price: 499000,
            originalPrice: 549000,
            specs: '8 cores, 16 threads, 5.5 GHz boost',
            features: ['Zen 5', 'PCIe 5.0', 'DDR5-5200'],
            socket: 'AM5',
            cores: 8,
            threads: 16,
            baseClock: 3.8,
            boostClock: 5.5,
            tdp: 65,
            powerDraw: 88,
            performanceScore: 88,
            category: 'high-end',
            compatibility: ['X870E', 'X870', 'X670E', 'X670', 'B650E', 'B650'],
            image: '🎯'
        },
        {
            id: 'cpu_6',
            name: 'AMD Ryzen 5 9600X',
            brand: 'AMD',
            price: 349000,
            originalPrice: 389000,
            specs: '6 cores, 12 threads, 5.4 GHz boost',
            features: ['Zen 5', 'PCIe 5.0', 'DDR5-5200'],
            socket: 'AM5',
            cores: 6,
            threads: 12,
            baseClock: 3.9,
            boostClock: 5.4,
            tdp: 65,
            powerDraw: 88,
            performanceScore: 82,
            category: 'mainstream',
            compatibility: ['X870E', 'X870', 'X670E', 'X670', 'B650E', 'B650'],
            image: '⭐'
        },
        // Intel 12th Gen (budget options)
        {
            id: 'cpu_7',
            name: 'Intel Core i3-12100F',
            brand: 'Intel',
            price: 89000,
            originalPrice: 99000,
            specs: '4 cores, 8 threads, 4.3 GHz boost',
            features: ['Budget Gaming', 'PCIe 4.0', 'DDR4/DDR5'],
            socket: 'LGA1700',
            cores: 4,
            threads: 8,
            baseClock: 3.3,
            boostClock: 4.3,
            tdp: 58,
            powerDraw: 89,
            performanceScore: 65,
            category: 'budget',
            compatibility: ['Z790', 'Z690', 'B760', 'B660', 'H770', 'H670'],
            image: '💡'
        },
        {
            id: 'cpu_8',
            name: 'Intel Core i5-12400F',
            brand: 'Intel',
            price: 149000,
            originalPrice: 169000,
            specs: '6 cores, 12 threads, 4.4 GHz boost',
            features: ['Great Value', 'PCIe 4.0', 'DDR4/DDR5'],
            socket: 'LGA1700',
            cores: 6,
            threads: 12,
            baseClock: 2.5,
            boostClock: 4.4,
            tdp: 65,
            powerDraw: 117,
            performanceScore: 75,
            category: 'budget',
            compatibility: ['Z790', 'Z690', 'B760', 'B660', 'H770', 'H670'],
            image: '🔧'
        },
        // AMD Ryzen 5000 Series (budget)
        {
            id: 'cpu_9',
            name: 'AMD Ryzen 5 5600',
            brand: 'AMD',
            price: 119000,
            originalPrice: 139000,
            specs: '6 cores, 12 threads, 4.4 GHz boost',
            features: ['Zen 3', 'PCIe 4.0', 'DDR4-3200'],
            socket: 'AM4',
            cores: 6,
            threads: 12,
            baseClock: 3.5,
            boostClock: 4.4,
            tdp: 65,
            powerDraw: 76,
            performanceScore: 78,
            category: 'budget',
            compatibility: ['B550', 'X570', 'A520', 'B450'],
            image: '🟠'
        },
        {
            id: 'cpu_10',
            name: 'AMD Ryzen 3 4300G',
            brand: 'AMD',
            price: 79000,
            originalPrice: 89000,
            specs: '4 cores, 8 threads, 4.0 GHz boost, integrated GPU',
            features: ['APU', 'Integrated Graphics', 'DDR4-3200'],
            socket: 'AM4',
            cores: 4,
            threads: 8,
            baseClock: 3.8,
            boostClock: 4.0,
            tdp: 65,
            powerDraw: 65,
            performanceScore: 55,
            category: 'budget',
            compatibility: ['B550', 'A520', 'B450'],
            image: '🔰'
        }
    ],

    gpu: [
        // NVIDIA RTX 40 Super Series
        {
            id: 'gpu_1',
            name: 'NVIDIA RTX 4090',
            brand: 'NVIDIA',
            price: 2299000,
            originalPrice: 2499000,
            specs: '24GB GDDR6X, 16384 CUDA cores, 2520 MHz boost',
            features: ['DLSS 3.5', 'Ray Tracing', '4K Gaming'],
            memory: 24576,
            memoryType: 'GDDR6X',
            coreClock: 2230,
            boostClock: 2520,
            memoryBandwidth: 1008,
            tdp: 450,
            powerDraw: 450,
            performanceScore: 100,
            category: 'flagship',
            connectors: ['3x DisplayPort 1.4a', '1x HDMI 2.1'],
            pcieLanes: 16,
            length: 336,
            slots: 3.5,
            image: '👑'
        },
        {
            id: 'gpu_2',
            name: 'NVIDIA RTX 4080 SUPER',
            brand: 'NVIDIA',
            price: 1499000,
            originalPrice: 1699000,
            specs: '16GB GDDR6X, 10240 CUDA cores, 2550 MHz boost',
            features: ['DLSS 3.5', 'Ray Tracing', '4K Gaming'],
            memory: 16384,
            memoryType: 'GDDR6X',
            coreClock: 2295,
            boostClock: 2550,
            memoryBandwidth: 736,
            tdp: 320,
            powerDraw: 320,
            performanceScore: 90,
            category: 'high-end',
            connectors: ['3x DisplayPort 1.4a', '1x HDMI 2.1'],
            pcieLanes: 16,
            length: 310,
            slots: 2.7,
            image: '💫'
        },
        {
            id: 'gpu_3',
            name: 'NVIDIA RTX 4070 Ti SUPER',
            brand: 'NVIDIA',
            price: 1099000,
            originalPrice: 1199000,
            specs: '16GB GDDR6X, 8448 CUDA cores, 2610 MHz boost',
            features: ['DLSS 3.5', 'Ray Tracing', '1440p Gaming'],
            memory: 16384,
            memoryType: 'GDDR6X',
            coreClock: 2340,
            boostClock: 2610,
            memoryBandwidth: 672,
            tdp: 285,
            powerDraw: 285,
            performanceScore: 82,
            category: 'high-end',
            connectors: ['3x DisplayPort 1.4a', '1x HDMI 2.1'],
            pcieLanes: 16,
            length: 295,
            slots: 2.5,
            image: '🎮'
        },
        // AMD RX 7000 Series
        {
            id: 'gpu_4',
            name: 'AMD Radeon RX 7900 XTX',
            brand: 'AMD',
            price: 1299000,
            originalPrice: 1499000,
            specs: '24GB GDDR6, 6144 Stream processors, 2500 MHz boost',
            features: ['RDNA 3', 'Ray Tracing', '4K Gaming'],
            memory: 24576,
            memoryType: 'GDDR6',
            coreClock: 2230,
            boostClock: 2500,
            memoryBandwidth: 960,
            tdp: 355,
            powerDraw: 355,
            performanceScore: 88,
            category: 'flagship',
            connectors: ['2x DisplayPort 2.1', '2x HDMI 2.1'],
            pcieLanes: 16,
            length: 320,
            slots: 2.8,
            image: '🔴'
        },
        {
            id: 'gpu_5',
            name: 'AMD Radeon RX 7800 XT',
            brand: 'AMD',
            price: 699000,
            originalPrice: 799000,
            specs: '16GB GDDR6, 3840 Stream processors, 2430 MHz boost',
            features: ['RDNA 3', 'Ray Tracing', '1440p Gaming'],
            memory: 16384,
            memoryType: 'GDDR6',
            coreClock: 2124,
            boostClock: 2430,
            memoryBandwidth: 624,
            tdp: 263,
            powerDraw: 263,
            performanceScore: 78,
            category: 'high-end',
            connectors: ['2x DisplayPort 2.1', '2x HDMI 2.1'],
            pcieLanes: 16,
            length: 295,
            slots: 2.5,
            image: '🎯'
        },
        {
            id: 'gpu_6',
            name: 'NVIDIA RTX 4060 Ti',
            brand: 'NVIDIA',
            price: 549000,
            originalPrice: 599000,
            specs: '16GB GDDR6, 4352 CUDA cores, 2540 MHz boost',
            features: ['DLSS 3.0', 'Ray Tracing', '1440p Gaming'],
            memory: 16384,
            memoryType: 'GDDR6',
            coreClock: 2310,
            boostClock: 2540,
            memoryBandwidth: 288,
            tdp: 165,
            powerDraw: 165,
            performanceScore: 72,
            category: 'mainstream',
            connectors: ['3x DisplayPort 1.4a', '1x HDMI 2.1'],
            pcieLanes: 8,
            length: 245,
            slots: 2,
            image: '⚡'
        },
        // Mid-range and budget GPUs
        {
            id: 'gpu_7',
            name: 'NVIDIA RTX 3060',
            brand: 'NVIDIA',
            price: 359000,
            originalPrice: 399000,
            specs: '8GB GDDR6, 3584 CUDA cores, 1777 MHz boost',
            features: ['DLSS 3.0', 'Ray Tracing', '1080p Gaming'],
            memory: 8192,
            memoryType: 'GDDR6',
            coreClock: 1320,
            boostClock: 1777,
            memoryBandwidth: 360,
            tdp: 170,
            powerDraw: 170,
            performanceScore: 68,
            category: 'mainstream',
            connectors: ['3x DisplayPort 1.4a', '1x HDMI 2.1'],
            pcieLanes: 8,
            length: 242,
            slots: 2,
            image: '🎪'
        },
        {
            id: 'gpu_8',
            name: 'AMD Radeon RX 6600',
            brand: 'AMD',
            price: 279000,
            originalPrice: 329000,
            specs: '8GB GDDR6, 1792 Stream processors, 2491 MHz boost',
            features: ['RDNA 2', 'Ray Tracing', '1080p Gaming'],
            memory: 8192,
            memoryType: 'GDDR6',
            coreClock: 2044,
            boostClock: 2491,
            memoryBandwidth: 224,
            tdp: 132,
            powerDraw: 132,
            performanceScore: 62,
            category: 'budget',
            connectors: ['2x DisplayPort 1.4a', '2x HDMI 2.1'],
            pcieLanes: 8,
            length: 240,
            slots: 2,
            image: '🟡'
        },
        {
            id: 'gpu_9',
            name: 'NVIDIA GTX 1660 SUPER',
            brand: 'NVIDIA',
            price: 199000,
            originalPrice: 229000,
            specs: '6GB GDDR6, 1408 CUDA cores, 1785 MHz boost',
            features: ['Budget Gaming', 'No RT', '1080p High'],
            memory: 6144,
            memoryType: 'GDDR6',
            coreClock: 1530,
            boostClock: 1785,
            memoryBandwidth: 336,
            tdp: 125,
            powerDraw: 125,
            performanceScore: 55,
            category: 'budget',
            connectors: ['1x DisplayPort 1.4', '1x HDMI 2.0b', '1x DVI-D'],
            pcieLanes: 8,
            length: 227,
            slots: 2,
            image: '🟢'
        },
        {
            id: 'gpu_10',
            name: 'NVIDIA GTX 1080',
            brand: 'NVIDIA',
            price: 149000,
            originalPrice: 179000,
            specs: '8GB GDDR5X, 2560 CUDA cores, 1733 MHz boost',
            features: ['Legacy High-End', 'VR Ready', '1440p Gaming'],
            memory: 8192,
            memoryType: 'GDDR5X',
            coreClock: 1607,
            boostClock: 1733,
            memoryBandwidth: 320,
            tdp: 180,
            powerDraw: 180,
            performanceScore: 58,
            category: 'budget',
            connectors: ['3x DisplayPort 1.4', '1x HDMI 2.0b', '1x DVI-D'],
            pcieLanes: 8,
            length: 280,
            slots: 2,
            image: '⚪'
        },
        {
            id: 'gpu_11',
            name: 'AMD Radeon RX 580',
            brand: 'AMD',
            price: 129000,
            originalPrice: 149000,
            specs: '8GB GDDR5, 2304 Stream processors, 1366 MHz boost',
            features: ['Budget Gaming', 'FreeSync', '1080p Medium'],
            memory: 8192,
            memoryType: 'GDDR5',
            coreClock: 1257,
            boostClock: 1366,
            memoryBandwidth: 256,
            tdp: 185,
            powerDraw: 185,
            performanceScore: 48,
            category: 'budget',
            connectors: ['3x DisplayPort 1.4', '1x HDMI 2.0', '1x DVI-D'],
            pcieLanes: 8,
            length: 241,
            slots: 2,
            image: '🟤'
        },
        {
            id: 'gpu_12',
            name: 'NVIDIA GT 1030',
            brand: 'NVIDIA',
            price: 49000,
            originalPrice: 59000,
            specs: '2GB GDDR5, 384 CUDA cores, 1468 MHz boost',
            features: ['Entry Level', 'Low Profile', 'HTPC'],
            memory: 2048,
            memoryType: 'GDDR5',
            coreClock: 1227,
            boostClock: 1468,
            memoryBandwidth: 48,
            tdp: 30,
            powerDraw: 30,
            performanceScore: 25,
            category: 'entry',
            connectors: ['1x DisplayPort 1.4', '1x HDMI 2.0'],
            pcieLanes: 4,
            length: 147,
            slots: 1,
            image: '🔵'
        }
    ],

    motherboard: [
        // Intel Z790 Chipset
        {
            id: 'mb_1',
            name: 'ASUS ROG Maximus Z790 HERO',
            brand: 'ASUS',
            price: 749000,
            originalPrice: 849000,
            specs: 'ATX, LGA1700, Z790 chipset',
            features: ['WiFi 7', 'DDR5-7800', 'PCIe 5.0'],
            socket: 'LGA1700',
            chipset: 'Z790',
            formFactor: 'ATX',
            memorySlots: 4,
            maxMemory: 128,
            memoryTypes: ['DDR5-7800', 'DDR5-7600', 'DDR5-7200'],
            pciSlots: ['1x PCIe 5.0 x16', '1x PCIe 4.0 x16', '2x PCIe 4.0 x1'],
            m2Slots: 5,
            sataPortsCount: 8,
            usbPorts: 14,
            networkSpeed: 2500,
            wifi: 'WiFi 7',
            bluetooth: '5.4',
            audioCodec: 'SupremeFX 7.1',
            powerConnectors: ['24-pin ATX', '8+4 pin CPU'],
            performanceScore: 95,
            category: 'flagship',
            compatibility: ['14th Gen Intel', '13th Gen Intel', '12th Gen Intel'],
            image: '🏆'
        },
        {
            id: 'mb_2',
            name: 'MSI MAG Z790 TOMAHAWK WIFI',
            brand: 'MSI',
            price: 449000,
            originalPrice: 499000,
            specs: 'ATX, LGA1700, Z790 chipset',
            features: ['WiFi 6E', 'DDR5-7200', 'PCIe 5.0'],
            socket: 'LGA1700',
            chipset: 'Z790',
            formFactor: 'ATX',
            memorySlots: 4,
            maxMemory: 128,
            memoryTypes: ['DDR5-7200', 'DDR5-6800', 'DDR5-6400'],
            pciSlots: ['1x PCIe 5.0 x16', '1x PCIe 4.0 x16', '2x PCIe 3.0 x1'],
            m2Slots: 4,
            sataPortsCount: 6,
            usbPorts: 12,
            networkSpeed: 2500,
            wifi: 'WiFi 6E',
            bluetooth: '5.3',
            audioCodec: 'Realtek ALC4080',
            powerConnectors: ['24-pin ATX', '8+4 pin CPU'],
            performanceScore: 88,
            category: 'high-end',
            compatibility: ['14th Gen Intel', '13th Gen Intel', '12th Gen Intel'],
            image: '⚔️'
        },
        // AMD X870E Chipset
        {
            id: 'mb_3',
            name: 'ASUS ROG Crosshair X870E HERO',
            brand: 'ASUS',
            price: 799000,
            originalPrice: 899000,
            specs: 'ATX, AM5, X870E chipset',
            features: ['WiFi 7', 'DDR5-8000', 'PCIe 5.0', 'USB4'],
            socket: 'AM5',
            chipset: 'X870E',
            formFactor: 'ATX',
            memorySlots: 4,
            maxMemory: 128,
            memoryTypes: ['DDR5-8000', 'DDR5-7600', 'DDR5-7200'],
            pciSlots: ['2x PCIe 5.0 x16', '1x PCIe 4.0 x16', '2x PCIe 4.0 x1'],
            m2Slots: 4,
            sataPortsCount: 8,
            usbPorts: 16,
            networkSpeed: 2500,
            wifi: 'WiFi 7',
            bluetooth: '5.4',
            audioCodec: 'SupremeFX 7.1',
            powerConnectors: ['24-pin ATX', '8+4 pin CPU'],
            performanceScore: 96,
            category: 'flagship',
            compatibility: ['AMD Ryzen 9000', 'AMD Ryzen 8000G', 'AMD Ryzen 7000'],
            image: '🎭'
        },
        {
            id: 'mb_4',
            name: 'MSI MAG X870 TOMAHAWK WIFI',
            brand: 'MSI',
            price: 399000,
            originalPrice: 449000,
            specs: 'ATX, AM5, X870 chipset',
            features: ['WiFi 6E', 'DDR5-7200', 'PCIe 5.0'],
            socket: 'AM5',
            chipset: 'X870',
            formFactor: 'ATX',
            memorySlots: 4,
            maxMemory: 128,
            memoryTypes: ['DDR5-7200', 'DDR5-6800', 'DDR5-6400'],
            pciSlots: ['1x PCIe 5.0 x16', '1x PCIe 4.0 x16', '2x PCIe 3.0 x1'],
            m2Slots: 4,
            sataPortsCount: 6,
            usbPorts: 14,
            networkSpeed: 2500,
            wifi: 'WiFi 6E',
            bluetooth: '5.3',
            audioCodec: 'Realtek ALC4080',
            powerConnectors: ['24-pin ATX', '8+4 pin CPU'],
            performanceScore: 90,
            category: 'high-end',
            compatibility: ['AMD Ryzen 9000', 'AMD Ryzen 8000G', 'AMD Ryzen 7000'],
            image: '🎯'
        },
        // Budget motherboards
        {
            id: 'mb_5',
            name: 'MSI B760M PRO-B DDR4',
            brand: 'MSI',
            price: 189000,
            originalPrice: 209000,
            specs: 'mATX, LGA1700, B760 chipset',
            features: ['DDR4-4800', 'PCIe 4.0', 'Budget Build'],
            socket: 'LGA1700',
            chipset: 'B760',
            formFactor: 'mATX',
            memorySlots: 2,
            maxMemory: 64,
            memoryTypes: ['DDR4-4800', 'DDR4-4000', 'DDR4-3200'],
            pciSlots: ['1x PCIe 4.0 x16', '1x PCIe 3.0 x1'],
            m2Slots: 2,
            sataPortsCount: 4,
            usbPorts: 8,
            networkSpeed: 1000,
            wifi: 'None',
            bluetooth: 'None',
            audioCodec: 'Realtek ALC897',
            powerConnectors: ['24-pin ATX', '8-pin CPU'],
            performanceScore: 75,
            category: 'budget',
            compatibility: ['14th Gen Intel', '13th Gen Intel', '12th Gen Intel'],
            image: '🛠️'
        },
        {
            id: 'mb_6',
            name: 'ASRock H670M-HDV',
            brand: 'ASRock',
            price: 149000,
            originalPrice: 169000,
            specs: 'mATX, LGA1700, H670 chipset',
            features: ['DDR4-4000', 'Budget', 'Basic Features'],
            socket: 'LGA1700',
            chipset: 'H670',
            formFactor: 'mATX',
            memorySlots: 2,
            maxMemory: 64,
            memoryTypes: ['DDR4-4000', 'DDR4-3200', 'DDR4-2933'],
            pciSlots: ['1x PCIe 4.0 x16', '2x PCIe 3.0 x1'],
            m2Slots: 1,
            sataPortsCount: 4,
            usbPorts: 6,
            networkSpeed: 1000,
            wifi: 'None',
            bluetooth: 'None',
            audioCodec: 'Realtek ALC887',
            powerConnectors: ['24-pin ATX', '8-pin CPU'],
            performanceScore: 65,
            category: 'budget',
            compatibility: ['12th Gen Intel', '13th Gen Intel'],
            image: '🔩'
        },
        // AMD Budget Motherboards
        {
            id: 'mb_7',
            name: 'MSI B550M PRO-B',
            brand: 'MSI',
            price: 159000,
            originalPrice: 179000,
            specs: 'mATX, AM4, B550 chipset',
            features: ['DDR4-4400', 'PCIe 4.0', 'Ryzen Ready'],
            socket: 'AM4',
            chipset: 'B550',
            formFactor: 'mATX',
            memorySlots: 2,
            maxMemory: 64,
            memoryTypes: ['DDR4-4400', 'DDR4-3200', 'DDR4-2933'],
            pciSlots: ['1x PCIe 4.0 x16', '1x PCIe 3.0 x1'],
            m2Slots: 2,
            sataPortsCount: 4,
            usbPorts: 8,
            networkSpeed: 1000,
            wifi: 'None',
            bluetooth: 'None',
            audioCodec: 'Realtek ALC892',
            powerConnectors: ['24-pin ATX', '8-pin CPU'],
            performanceScore: 72,
            category: 'budget',
            compatibility: ['AMD Ryzen 5000', 'AMD Ryzen 4000G', 'AMD Ryzen 3000'],
            image: '🔴'
        },
        {
            id: 'mb_8',
            name: 'ASUS PRIME A520M-K',
            brand: 'ASUS',
            price: 99000,
            originalPrice: 119000,
            specs: 'mATX, AM4, A520 chipset',
            features: ['DDR4-3200', 'Entry Level', 'Basic Build'],
            socket: 'AM4',
            chipset: 'A520',
            formFactor: 'mATX',
            memorySlots: 2,
            maxMemory: 32,
            memoryTypes: ['DDR4-3200', 'DDR4-2933', 'DDR4-2666'],
            pciSlots: ['1x PCIe 3.0 x16', '2x PCIe 3.0 x1'],
            m2Slots: 1,
            sataPortsCount: 4,
            usbPorts: 6,
            networkSpeed: 1000,
            wifi: 'None',
            bluetooth: 'None',
            audioCodec: 'Realtek ALC887',
            powerConnectors: ['24-pin ATX', '8-pin CPU'],
            performanceScore: 55,
            category: 'budget',
            compatibility: ['AMD Ryzen 5000', 'AMD Ryzen 4000G', 'AMD Ryzen 3000'],
            image: '🔶'
        }
    ],

    ram: [
        // DDR5 High Performance
        {
            id: 'ram_1',
            name: 'G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5-7200',
            brand: 'G.Skill',
            price: 269000,
            originalPrice: 299000,
            specs: '32GB (2x16GB), DDR5-7200, CL34-45-45-115',
            features: ['RGB Lighting', 'XMP 3.0', 'Ultra Low Latency'],
            capacity: 32,
            speed: 7200,
            type: 'DDR5',
            modules: 2,
            moduleSize: 16,
            timing: 'CL34-45-45-115',
            voltage: 1.45,
            features_list: ['RGB', 'XMP', 'Overclockable'],
            performanceScore: 95,
            category: 'flagship',
            compatibility: ['Intel Z790', 'Intel Z690', 'AMD X870E', 'AMD X870'],
            image: '🌈'
        },
        {
            id: 'ram_2',
            name: 'Corsair Dominator Platinum RGB 32GB (2x16GB) DDR5-6400',
            brand: 'Corsair',
            price: 229000,
            originalPrice: 259000,
            specs: '32GB (2x16GB), DDR5-6400, CL32-39-39-102',
            features: ['RGB Lighting', 'XMP 3.0', 'Premium Build'],
            capacity: 32,
            speed: 6400,
            type: 'DDR5',
            modules: 2,
            moduleSize: 16,
            timing: 'CL32-39-39-102',
            voltage: 1.40,
            features_list: ['RGB', 'XMP', 'Premium'],
            performanceScore: 90,
            category: 'high-end',
            compatibility: ['Intel Z790', 'Intel Z690', 'AMD X870E', 'AMD X870', 'AMD B650'],
            image: '💎'
        },
        {
            id: 'ram_3',
            name: 'Kingston FURY Beast 32GB (2x16GB) DDR5-5600',
            brand: 'Kingston',
            price: 169000,
            originalPrice: 199000,
            specs: '32GB (2x16GB), DDR5-5600, CL36-38-38-80',
            features: ['Intel XMP 3.0', 'AMD EXPO', 'Plug N Play'],
            capacity: 32,
            speed: 5600,
            type: 'DDR5',
            modules: 2,
            moduleSize: 16,
            timing: 'CL36-38-38-80',
            voltage: 1.25,
            features_list: ['XMP', 'EXPO', 'Reliable'],
            performanceScore: 82,
            category: 'mainstream',
            compatibility: ['Intel Z790', 'Intel B760', 'AMD X870', 'AMD B650'],
            image: '⚡'
        },
        {
            id: 'ram_4',
            name: 'G.Skill Trident Z5 Neo RGB 64GB (2x32GB) DDR5-6000',
            brand: 'G.Skill',
            price: 449000,
            originalPrice: 499000,
            specs: '64GB (2x32GB), DDR5-6000, CL30-40-40-96',
            features: ['RGB Lighting', 'AMD EXPO', 'Optimized for AMD'],
            capacity: 64,
            speed: 6000,
            type: 'DDR5',
            modules: 2,
            moduleSize: 32,
            timing: 'CL30-40-40-96',
            voltage: 1.35,
            features_list: ['RGB', 'EXPO', 'High Capacity'],
            performanceScore: 93,
            category: 'flagship',
            compatibility: ['AMD X870E', 'AMD X870', 'AMD B650E', 'Intel Z790'],
            image: '🚀'
        },
        // DDR4 RAM Options
        {
            id: 'ram_5',
            name: 'Corsair Vengeance LPX 16GB (2x8GB) DDR4-3200',
            brand: 'Corsair',
            price: 89000,
            originalPrice: 109000,
            specs: '16GB (2x8GB), DDR4-3200, CL16-18-18-36',
            features: ['XMP 2.0', 'Low Profile', 'Great Value'],
            capacity: 16,
            speed: 3200,
            type: 'DDR4',
            modules: 2,
            moduleSize: 8,
            timing: 'CL16-18-18-36',
            voltage: 1.35,
            features_list: ['XMP', 'Low Profile', 'Reliable'],
            performanceScore: 68,
            category: 'budget',
            compatibility: ['Intel Z790', 'Intel B760', 'AMD B550', 'AMD A520'],
            image: '⚙️'
        },
        {
            id: 'ram_6',
            name: 'G.Skill Ripjaws V 16GB (2x8GB) DDR4-3600',
            brand: 'G.Skill',
            price: 99000,
            originalPrice: 119000,
            specs: '16GB (2x8GB), DDR4-3600, CL18-22-22-42',
            features: ['XMP 2.0', 'AMD Optimized', 'High Speed'],
            capacity: 16,
            speed: 3600,
            type: 'DDR4',
            modules: 2,
            moduleSize: 8,
            timing: 'CL18-22-22-42',
            voltage: 1.35,
            features_list: ['XMP', 'AMD Optimized', 'Fast'],
            performanceScore: 72,
            category: 'budget',
            compatibility: ['Intel Z790', 'Intel B760', 'AMD B550', 'AMD X570'],
            image: '🏃'
        },
        {
            id: 'ram_7',
            name: 'Kingston FURY Beast 8GB (1x8GB) DDR4-2666',
            brand: 'Kingston',
            price: 39000,
            originalPrice: 49000,
            specs: '8GB (1x8GB), DDR4-2666, CL16-17-17-39',
            features: ['Plug N Play', 'Single Module', 'Entry Level'],
            capacity: 8,
            speed: 2666,
            type: 'DDR4',
            modules: 1,
            moduleSize: 8,
            timing: 'CL16-17-17-39',
            voltage: 1.2,
            features_list: ['Basic', 'Entry Level', 'Budget'],
            performanceScore: 45,
            category: 'budget',
            compatibility: ['Intel B760', 'Intel H670', 'AMD A520', 'AMD B450'],
            image: '🐥'
        },
        {
            id: 'ram_8',
            name: 'Corsair Vengeance LPX 32GB (2x16GB) DDR4-3200',
            brand: 'Corsair',
            price: 159000,
            originalPrice: 189000,
            specs: '32GB (2x16GB), DDR4-3200, CL16-18-18-36',
            features: ['XMP 2.0', 'High Capacity', 'Content Creation'],
            capacity: 32,
            speed: 3200,
            type: 'DDR4',
            modules: 2,
            moduleSize: 16,
            timing: 'CL16-18-18-36',
            voltage: 1.35,
            features_list: ['XMP', 'High Capacity', 'Work'],
            performanceScore: 75,
            category: 'mainstream',
            compatibility: ['Intel Z790', 'Intel B760', 'AMD B550', 'AMD X570'],
            image: '💼'
        },
        // Budget DDR5
        {
            id: 'ram_9',
            name: 'Corsair Vengeance 16GB (2x8GB) DDR5-4800',
            brand: 'Corsair',
            price: 119000,
            originalPrice: 139000,
            specs: '16GB (2x8GB), DDR5-4800, CL40-40-40-77',
            features: ['JEDEC Standard', 'Entry DDR5', 'Future Ready'],
            capacity: 16,
            speed: 4800,
            type: 'DDR5',
            modules: 2,
            moduleSize: 8,
            timing: 'CL40-40-40-77',
            voltage: 1.1,
            features_list: ['DDR5', 'Entry Level', 'Future Proof'],
            performanceScore: 65,
            category: 'budget',
            compatibility: ['Intel Z790', 'Intel B760', 'AMD X870', 'AMD B650'],
            image: '🎆'
        }
    ],

    storage: [
        // NVMe SSD PCIe 5.0
        {
            id: 'storage_1',
            name: 'Samsung 990 PRO 4TB PCIe 4.0 NVMe SSD',
            brand: 'Samsung',
            price: 549000,
            originalPrice: 649000,
            specs: '4TB, PCIe 4.0, up to 7,450 MB/s read',
            features: ['PCIe 4.0', 'V-NAND', '5 Year Warranty'],
            capacity: 4096,
            type: 'NVMe SSD',
            interface: 'PCIe 4.0 x4',
            formFactor: 'M.2 2280',
            readSpeed: 7450,
            writeSpeed: 6900,
            iopsRead: 1400000,
            iopsWrite: 1550000,
            endurance: 2400,
            warranty: 5,
            performanceScore: 98,
            category: 'flagship',
            compatibility: ['PCIe 4.0', 'PCIe 5.0', 'M.2'],
            image: '💾'
        },
        {
            id: 'storage_2',
            name: 'Western Digital WD_BLACK SN850X 2TB',
            brand: 'Western Digital',
            price: 299000,
            originalPrice: 349000,
            specs: '2TB, PCIe 4.0, up to 7,300 MB/s read',
            features: ['Gaming Optimized', 'Heatsink Option', '5 Year Warranty'],
            capacity: 2048,
            type: 'NVMe SSD',
            interface: 'PCIe 4.0 x4',
            formFactor: 'M.2 2280',
            readSpeed: 7300,
            writeSpeed: 6600,
            iopsRead: 1200000,
            iopsWrite: 1100000,
            endurance: 1200,
            warranty: 5,
            performanceScore: 95,
            category: 'high-end',
            compatibility: ['PCIe 4.0', 'PCIe 5.0', 'M.2'],
            image: '🎮'
        },
        {
            id: 'storage_3',
            name: 'Crucial P5 Plus 1TB PCIe 4.0 NVMe SSD',
            brand: 'Crucial',
            price: 149000,
            originalPrice: 179000,
            specs: '1TB, PCIe 4.0, up to 6,600 MB/s read',
            features: ['Micron 3D NAND', 'Power Efficient', '5 Year Warranty'],
            capacity: 1024,
            type: 'NVMe SSD',
            interface: 'PCIe 4.0 x4',
            formFactor: 'M.2 2280',
            readSpeed: 6600,
            writeSpeed: 5000,
            iopsRead: 900000,
            iopsWrite: 800000,
            endurance: 600,
            warranty: 5,
            performanceScore: 88,
            category: 'mainstream',
            compatibility: ['PCIe 4.0', 'PCIe 5.0', 'M.2'],
            image: '⚡'
        },
        {
            id: 'storage_4',
            name: 'Seagate IronWolf Pro 8TB HDD',
            brand: 'Seagate',
            price: 179000,
            originalPrice: 199000,
            specs: '8TB, 7200 RPM, 256MB cache',
            features: ['NAS Optimized', 'CMR Technology', '5 Year Warranty'],
            capacity: 8192,
            type: 'HDD',
            interface: 'SATA III',
            formFactor: '3.5"',
            readSpeed: 261,
            writeSpeed: 261,
            rpm: 7200,
            cache: 256,
            warranty: 5,
            performanceScore: 65,
            category: 'storage',
            compatibility: ['SATA III'],
            image: '📚'
        },
        // Budget Storage Options
        {
            id: 'storage_5',
            name: 'Kingston NV2 500GB PCIe 4.0 NVMe SSD',
            brand: 'Kingston',
            price: 79000,
            originalPrice: 89000,
            specs: '500GB, PCIe 4.0, up to 3,500 MB/s read',
            features: ['Budget NVMe', 'PCIe 4.0', '3 Year Warranty'],
            capacity: 512,
            type: 'NVMe SSD',
            interface: 'PCIe 4.0 x4',
            formFactor: 'M.2 2280',
            readSpeed: 3500,
            writeSpeed: 2100,
            iopsRead: 300000,
            iopsWrite: 250000,
            endurance: 160,
            warranty: 3,
            performanceScore: 72,
            category: 'budget',
            compatibility: ['PCIe 4.0', 'PCIe 5.0', 'M.2'],
            image: '🖾'
        },
        {
            id: 'storage_6',
            name: 'WD Blue SN570 1TB PCIe 3.0 NVMe SSD',
            brand: 'Western Digital',
            price: 99000,
            originalPrice: 119000,
            specs: '1TB, PCIe 3.0, up to 3,500 MB/s read',
            features: ['Reliable', 'Good Value', '5 Year Warranty'],
            capacity: 1024,
            type: 'NVMe SSD',
            interface: 'PCIe 3.0 x4',
            formFactor: 'M.2 2280',
            readSpeed: 3500,
            writeSpeed: 3000,
            iopsRead: 400000,
            iopsWrite: 380000,
            endurance: 600,
            warranty: 5,
            performanceScore: 78,
            category: 'budget',
            compatibility: ['PCIe 3.0', 'PCIe 4.0', 'M.2'],
            image: '🔵'
        },
        {
            id: 'storage_7',
            name: 'Samsung 970 EVO Plus 500GB PCIe 3.0 NVMe SSD',
            brand: 'Samsung',
            price: 89000,
            originalPrice: 109000,
            specs: '500GB, PCIe 3.0, up to 3,500 MB/s read',
            features: ['Samsung Quality', 'TurboWrite', '5 Year Warranty'],
            capacity: 512,
            type: 'NVMe SSD',
            interface: 'PCIe 3.0 x4',
            formFactor: 'M.2 2280',
            readSpeed: 3500,
            writeSpeed: 3200,
            iopsRead: 480000,
            iopsWrite: 550000,
            endurance: 300,
            warranty: 5,
            performanceScore: 80,
            category: 'mainstream',
            compatibility: ['PCIe 3.0', 'PCIe 4.0', 'M.2'],
            image: '⭐'
        },
        {
            id: 'storage_8',
            name: 'WD Blue 1TB HDD 7200 RPM',
            brand: 'Western Digital',
            price: 49000,
            originalPrice: 59000,
            specs: '1TB, 7200 RPM, 64MB cache',
            features: ['Budget Storage', 'Mass Storage', '2 Year Warranty'],
            capacity: 1024,
            type: 'HDD',
            interface: 'SATA III',
            formFactor: '3.5"',
            readSpeed: 150,
            writeSpeed: 150,
            rpm: 7200,
            cache: 64,
            warranty: 2,
            performanceScore: 35,
            category: 'budget',
            compatibility: ['SATA III'],
            image: '💿'
        },
        {
            id: 'storage_9',
            name: 'Crucial BX500 240GB SATA SSD',
            brand: 'Crucial',
            price: 39000,
            originalPrice: 49000,
            specs: '240GB, SATA III, up to 540 MB/s read',
            features: ['Entry Level SSD', 'Reliable', '3 Year Warranty'],
            capacity: 240,
            type: 'SATA SSD',
            interface: 'SATA III',
            formFactor: '2.5"',
            readSpeed: 540,
            writeSpeed: 500,
            iopsRead: 95000,
            iopsWrite: 90000,
            endurance: 80,
            warranty: 3,
            performanceScore: 50,
            category: 'budget',
            compatibility: ['SATA III'],
            image: '🕸️'
        }
    ],

    psu: [
        // 80+ Titanium PSUs
        {
            id: 'psu_1',
            name: 'Corsair AX1600i 1600W 80+ Titanium',
            brand: 'Corsair',
            price: 799000,
            originalPrice: 899000,
            specs: '1600W, 80+ Titanium, Fully Modular',
            features: ['Digital Monitoring', '10 Year Warranty', 'Zero RPM Mode'],
            wattage: 1600,
            efficiency: '80+ Titanium',
            modular: 'Fully Modular',
            fanSize: 140,
            cables: ['24-pin ATX', '2x 8-pin CPU', '8x PCIe', '12x SATA', '4x Molex'],
            protections: ['OVP', 'UVP', 'OCP', 'OTP', 'SCP', 'OPP'],
            warranty: 10,
            performanceScore: 98,
            category: 'flagship',
            compatibility: ['ATX', 'E-ATX'],
            image: '⚡'
        },
        {
            id: 'psu_2',
            name: 'Seasonic Prime PX-1300 1300W 80+ Platinum',
            brand: 'Seasonic',
            price: 569000,
            originalPrice: 629000,
            specs: '1300W, 80+ Platinum, Fully Modular',
            features: ['12 Year Warranty', 'Hybrid Fan Control', 'Premium Cables'],
            wattage: 1300,
            efficiency: '80+ Platinum',
            modular: 'Fully Modular',
            fanSize: 135,
            cables: ['24-pin ATX', '2x 8-pin CPU', '6x PCIe', '10x SATA', '4x Molex'],
            protections: ['OVP', 'UVP', 'OCP', 'OTP', 'SCP'],
            warranty: 12,
            performanceScore: 94,
            category: 'high-end',
            compatibility: ['ATX', 'E-ATX'],
            image: '🔋'
        },
        {
            id: 'psu_3',
            name: 'EVGA SuperNOVA 1000 G7 1000W 80+ Gold',
            brand: 'EVGA',
            price: 329000,
            originalPrice: 379000,
            specs: '1000W, 80+ Gold, Fully Modular',
            features: ['10 Year Warranty', 'Compact Design', 'Silent Operation'],
            wattage: 1000,
            efficiency: '80+ Gold',
            modular: 'Fully Modular',
            fanSize: 135,
            cables: ['24-pin ATX', '2x 8-pin CPU', '6x PCIe', '8x SATA', '4x Molex'],
            protections: ['OVP', 'UVP', 'OCP', 'OTP'],
            warranty: 10,
            performanceScore: 90,
            category: 'mainstream',
            compatibility: ['ATX', 'E-ATX'],
            image: '⚡'
        },
        {
            id: 'psu_4',
            name: 'be quiet! Dark Power Pro 12 850W 80+ Titanium',
            brand: 'be quiet!',
            price: 449000,
            originalPrice: 499000,
            specs: '850W, 80+ Titanium, Fully Modular',
            features: ['Silent Operation', '5 Year Warranty', 'Premium Components'],
            wattage: 850,
            efficiency: '80+ Titanium',
            modular: 'Fully Modular',
            fanSize: 135,
            cables: ['24-pin ATX', '2x 8-pin CPU', '6x PCIe', '8x SATA', '4x Molex'],
            protections: ['OVP', 'UVP', 'OCP', 'OTP', 'SCP'],
            warranty: 5,
            performanceScore: 92,
            category: 'high-end',
            compatibility: ['ATX'],
            image: '🔇'
        }
    ],

    case: [
        // Premium Cases
        {
            id: 'case_1',
            name: 'Lian Li O11 Dynamic EVO',
            brand: 'Lian Li',
            price: 249000,
            originalPrice: 279000,
            specs: 'Mid-Tower, Tempered Glass, E-ATX Support',
            features: ['Dual Chamber', 'Premium Build', 'Excellent Airflow'],
            formFactor: 'Mid-Tower',
            motherboardSupport: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'],
            maxGpuLength: 420,
            maxCpuCoolerHeight: 155,
            maxPsuLength: 200,
            frontPanelConnectors: ['USB-C', '2x USB 3.0', 'Audio'],
            expansionSlots: 8,
            driveBays: {
                '2.5inch': 6,
                '3.5inch': 0
            },
            fanSupport: {
                'front': '3x 120mm',
                'top': '3x 120mm',
                'bottom': '3x 120mm',
                'side': '3x 120mm'
            },
            radiatorSupport: ['360mm', '280mm', '240mm'],
            dimensions: {
                'length': 465,
                'width': 272,
                'height': 459
            },
            weight: 11.5,
            performanceScore: 95,
            category: 'flagship',
            compatibility: ['ATX PSU'],
            image: '💎'
        },
        {
            id: 'case_2',
            name: 'Fractal Design Define 7',
            brand: 'Fractal Design',
            price: 199000,
            originalPrice: 229000,
            specs: 'Full-Tower, Sound Dampened, E-ATX Support',
            features: ['Sound Dampening', 'Modular Interior', 'Premium Materials'],
            formFactor: 'Full-Tower',
            motherboardSupport: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'],
            maxGpuLength: 440,
            maxCpuCoolerHeight: 185,
            maxPsuLength: 300,
            frontPanelConnectors: ['USB-C', '2x USB 3.0', 'Audio'],
            expansionSlots: 8,
            driveBays: {
                '2.5inch': 6,
                '3.5inch': 6
            },
            fanSupport: {
                'front': '3x 140mm',
                'top': '3x 140mm',
                'rear': '1x 140mm'
            },
            radiatorSupport: ['420mm', '360mm', '280mm'],
            dimensions: {
                'length': 547,
                'width': 240,
                'height': 475
            },
            weight: 13.2,
            performanceScore: 90,
            category: 'high-end',
            compatibility: ['ATX PSU'],
            image: '🏗️'
        },
        {
            id: 'case_3',
            name: 'Cooler Master MasterBox TD500 Mesh',
            brand: 'Cooler Master',
            price: 129000,
            originalPrice: 149000,
            specs: 'Mid-Tower, Mesh Front, RGB',
            features: ['ARGB Lighting', 'Mesh Front Panel', 'Good Value'],
            formFactor: 'Mid-Tower',
            motherboardSupport: ['ATX', 'Micro-ATX', 'Mini-ITX'],
            maxGpuLength: 410,
            maxCpuCoolerHeight: 165,
            maxPsuLength: 180,
            frontPanelConnectors: ['2x USB 3.0', 'Audio'],
            expansionSlots: 7,
            driveBays: {
                '2.5inch': 2,
                '3.5inch': 2
            },
            fanSupport: {
                'front': '3x 120mm',
                'top': '2x 120mm',
                'rear': '1x 120mm'
            },
            radiatorSupport: ['240mm', '280mm'],
            dimensions: {
                'length': 457,
                'width': 210,
                'height': 453
            },
            weight: 6.8,
            performanceScore: 82,
            category: 'mainstream',
            compatibility: ['ATX PSU'],
            image: '🌈'
        }
    ],

    cooling: [
        // AIO Liquid Coolers
        {
            id: 'cooling_1',
            name: 'NZXT Kraken Z73 360mm AIO',
            brand: 'NZXT',
            price: 399000,
            originalPrice: 449000,
            specs: '360mm AIO, LCD Display, RGB',
            features: ['2.36" LCD Display', 'CAM Software', 'RGB Lighting'],
            type: 'AIO Liquid',
            radiatorSize: 360,
            fanCount: 3,
            fanSize: 120,
            pumpSpeed: 2800,
            noiseLevel: 21,
            socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
            dimensions: {
                'radiator': '394x120x27',
                'pump': '80x80x52'
            },
            warranty: 6,
            performanceScore: 96,
            category: 'flagship',
            compatibility: ['Intel', 'AMD'],
            image: '❄️'
        },
        {
            id: 'cooling_2',
            name: 'Corsair H150i ELITE CAPELLIX 360mm',
            brand: 'Corsair',
            price: 319000,
            originalPrice: 359000,
            specs: '360mm AIO, CAPELLIX RGB, iCUE',
            features: ['CAPELLIX RGB LEDs', 'iCUE Software', 'Zero RPM Mode'],
            type: 'AIO Liquid',
            radiatorSize: 360,
            fanCount: 3,
            fanSize: 120,
            pumpSpeed: 2400,
            noiseLevel: 20,
            socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
            dimensions: {
                'radiator': '397x120x27',
                'pump': '80x80x56'
            },
            warranty: 5,
            performanceScore: 94,
            category: 'high-end',
            compatibility: ['Intel', 'AMD'],
            image: '🌊'
        },
        // Air Coolers
        {
            id: 'cooling_3',
            name: 'Noctua NH-D15',
            brand: 'Noctua',
            price: 129000,
            originalPrice: 149000,
            specs: 'Dual Tower Air Cooler, 140mm fans',
            features: ['Dual Tower Design', 'Premium Fans', 'Excellent Performance'],
            type: 'Air Cooler',
            radiatorSize: null,
            fanCount: 2,
            fanSize: 140,
            pumpSpeed: null,
            noiseLevel: 24.6,
            socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
            dimensions: {
                'cooler': '165x150x161'
            },
            warranty: 6,
            performanceScore: 90,
            category: 'high-end',
            compatibility: ['Intel', 'AMD'],
            image: '🌪️'
        },
        {
            id: 'cooling_4',
            name: 'be quiet! Dark Rock Pro 4',
            brand: 'be quiet!',
            price: 99000,
            originalPrice: 119000,
            specs: 'Dual Tower Air Cooler, Silent Operation',
            features: ['Silent Operation', 'Black Coating', 'Premium Build'],
            type: 'Air Cooler',
            radiatorSize: null,
            fanCount: 2,
            fanSize: 135,
            pumpSpeed: null,
            noiseLevel: 12.8,
            socketSupport: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
            dimensions: {
                'cooler': '163x136x168'
            },
            warranty: 3,
            performanceScore: 88,
            category: 'mainstream',
            compatibility: ['Intel', 'AMD'],
            image: '🔇'
        }
    ]
};

// Prebuilt Configurations
const PREBUILT_CONFIGS = [
    {
        id: 'prebuild_1',
        name: 'Extreme Gaming Beast',
        description: 'A legvégső gaming élmény 4K@120FPS teljesítménnyel. Minden AAA játék maximális beállításokon.',
        badge: 'FLAGSHIP',
        price: 2799000,
        category: 'gaming',
        components: {
            cpu: 'cpu_1', // i9-14900KS
            gpu: 'gpu_1', // RTX 4090
            motherboard: 'mb_1', // ASUS ROG Z790 HERO
            ram: 'ram_1', // G.Skill 32GB DDR5-7200
            storage: 'storage_1', // Samsung 990 PRO 4TB
            psu: 'psu_1', // Corsair 1600W
            case: 'case_1', // Lian Li O11
            cooling: 'cooling_1' // NZXT Kraken Z73
        },
        specs: [
            'Intel i9-14900KS + RTX 4090',
            '32GB DDR5-7200 RAM',
            '4TB NVMe SSD',
            '1600W 80+ Titanium PSU'
        ],
        performance: {
            gaming: 100,
            work: 98,
            streaming: 100
        }
    },
    {
        id: 'prebuild_2',
        name: 'Content Creator Pro',
        description: 'Professzionális tartalomkészítéshez optimalizált konfiguráció. Videószerkesztés és streaming.',
        badge: 'CREATOR',
        price: 1899000,
        category: 'workstation',
        components: {
            cpu: 'cpu_4', // Ryzen 9 9950X
            gpu: 'gpu_4', // RX 7900 XTX
            motherboard: 'mb_3', // ASUS ROG X870E
            ram: 'ram_4', // G.Skill 64GB
            storage: 'storage_2', // WD SN850X 2TB
            psu: 'psu_2', // Seasonic 1300W
            case: 'case_2', // Fractal Define 7
            cooling: 'cooling_2' // Corsair H150i
        },
        specs: [
            'AMD Ryzen 9 9950X + RX 7900 XTX',
            '64GB DDR5-6000 RAM',
            '2TB NVMe SSD',
            '1300W 80+ Platinum PSU'
        ],
        performance: {
            gaming: 88,
            work: 100,
            streaming: 95
        }
    },
    {
        id: 'prebuild_3',
        name: 'High-End Gaming',
        description: '1440p és 4K gaming kiváló teljesítménnyel. Modern játékok magas FPS értékekkel.',
        badge: 'POPULAR',
        price: 1299000,
        category: 'gaming',
        components: {
            cpu: 'cpu_2', // i7-14700K
            gpu: 'gpu_2', // RTX 4080 SUPER
            motherboard: 'mb_2', // MSI Z790 TOMAHAWK
            ram: 'ram_2', // Corsair 32GB
            storage: 'storage_2', // WD SN850X 2TB
            psu: 'psu_3', // EVGA 1000W
            case: 'case_3', // CM TD500
            cooling: 'cooling_3' // Noctua NH-D15
        },
        specs: [
            'Intel i7-14700K + RTX 4080 SUPER',
            '32GB DDR5-6400 RAM',
            '2TB NVMe SSD',
            '1000W 80+ Gold PSU'
        ],
        performance: {
            gaming: 92,
            work: 88,
            streaming: 90
        }
    },
    {
        id: 'prebuild_4',
        name: 'Balanced Performance',
        description: '1440p gaming és produktivitás optimális ár-érték arányban. Kiváló választás mindennapi használatra.',
        badge: 'BEST VALUE',
        price: 899000,
        category: 'balanced',
        components: {
            cpu: 'cpu_5', // Ryzen 7 9700X
            gpu: 'gpu_5', // RX 7800 XT
            motherboard: 'mb_4', // MSI X870 TOMAHAWK
            ram: 'ram_3', // Kingston 32GB
            storage: 'storage_3', // Crucial P5 Plus 1TB
            psu: 'psu_4', // be quiet! 850W
            case: 'case_3', // CM TD500
            cooling: 'cooling_4' // be quiet! Dark Rock Pro 4
        },
        specs: [
            'AMD Ryzen 7 9700X + RX 7800 XT',
            '32GB DDR5-5600 RAM',
            '1TB NVMe SSD',
            '850W 80+ Titanium PSU'
        ],
        performance: {
            gaming: 82,
            work: 85,
            streaming: 78
        }
    }
];

// Compatibility Rules
const COMPATIBILITY_RULES = {
    cpu_motherboard: {
        'LGA1700': ['Z790', 'Z690', 'B760', 'B660', 'H770', 'H670'],
        'AM5': ['X870E', 'X870', 'X670E', 'X670', 'B650E', 'B650', 'A620'],
        'AM4': ['B550', 'X570', 'A520', 'B450', 'X470', 'B350']
    },
    ram_motherboard: {
        'Z790': ['DDR5', 'DDR4'],
        'Z690': ['DDR5', 'DDR4'],
        'B760': ['DDR5', 'DDR4'],
        'H670': ['DDR4'],
        'B660': ['DDR4'],
        'X870E': ['DDR5'],
        'X870': ['DDR5'],
        'X670E': ['DDR5'],
        'B650E': ['DDR5'],
        'B650': ['DDR5'],
        'B550': ['DDR4'],
        'X570': ['DDR4'],
        'A520': ['DDR4'],
        'B450': ['DDR4']
    },
    gpu_psu_requirements: {
        'RTX 4090': 850,
        'RTX 4080 SUPER': 750,
        'RTX 4070 Ti SUPER': 700,
        'RX 7900 XTX': 800,
        'RX 7800 XT': 700,
        'RTX 4060 Ti': 550,
        'RTX 3060': 550,
        'RX 6600': 500,
        'GTX 1660 SUPER': 450,
        'GTX 1080': 500,
        'RX 580': 500,
        'GT 1030': 300
    }
};

// Performance Benchmarks
const PERFORMANCE_BENCHMARKS = {
    gaming: {
        '4K Ultra': {
            'RTX 4090': 95,
            'RTX 4080 SUPER': 78,
            'RTX 4070 Ti SUPER': 65,
            'RX 7900 XTX': 72,
            'RX 7800 XT': 58,
            'RTX 4060 Ti': 45
        },
        '1440p Ultra': {
            'RTX 4090': 100,
            'RTX 4080 SUPER': 98,
            'RTX 4070 Ti SUPER': 92,
            'RX 7900 XTX': 95,
            'RX 7800 XT': 88,
            'RTX 4060 Ti': 78
        }
    },
    workstation: {
        'Video Editing': {
            'i9-14900KS': 98,
            'i7-14700K': 88,
            'i5-14600K': 75,
            'Ryzen 9 9950X': 100,
            'Ryzen 7 9700X': 85,
            'Ryzen 5 9600X': 72
        },
        '3D Rendering': {
            'i9-14900KS': 95,
            'i7-14700K': 82,
            'i5-14600K': 68,
            'Ryzen 9 9950X': 100,
            'Ryzen 7 9700X': 78,
            'Ryzen 5 9600X': 65
        }
    }
};